#!/bin/bash
# This script is used to remove the files that are either removed or modified
# to un the script ./ignore_modified_git_files.sh
# Should remve all untracked files
git status -s | grep -e "^\?\?" | grep -v ".gitignore" | cut -c 4- >> .gitignore
# Should automatically exclude these files leaving under 10 files(unable to get these to ignore these files)
git update-index --assume-unchanged .flutter-plugins
git update-index --assume-unchanged .gitignore
git update-index --assume-unchanged .idea/libraries/Dart_Packages.xml
git update-index --assume-unchanged .idea/libraries/Flutter_Plugins.xml
git update-index --assume-unchanged .idea/workspace.xml
git update-index --assume-unchanged .packages
git update-index --assume-unchanged android/.gradle/4.10.2/fileHashes/fileHashes.bin
git update-index --assume-unchanged android/.gradle/4.10.2/fileHashes/fileHashes.lock
git update-index --assume-unchanged android/.gradle/4.10.2/fileHashes/resourceHashesCache.bin
git update-index --assume-unchanged android/.gradle/4.10.2/javaCompile/classAnalysis.bin
git update-index --assume-unchanged android/.gradle/4.10.2/javaCompile/jarAnalysis.bin
git update-index --assume-unchanged android/.gradle/4.10.2/javaCompile/javaCompile.lock
git update-index --assume-unchanged android/.gradle/4.10.2/javaCompile/taskHistory.bin
git update-index --assume-unchanged android/.gradle/4.10.2/taskHistory/taskHistory.bin
git update-index --assume-unchanged android/.gradle/4.10.2/taskHistory/taskHistory.lock
git update-index --assume-unchanged android/.gradle/buildOutputCleanup/buildOutputCleanup.lock
git update-index --assume-unchanged android/.gradle/buildOutputCleanup/outputFiles.bin
git update-index --assume-unchanged android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
git update-index --assume-unchanged android/local.properties
git update-index --assume-unchanged build/app.dill.track.dill
git update-index --assume-unchanged build/app/generated/not_namespaced_r_class_sources/debug/processDebugResources/r/com/hikelocator/hikelocator/R.java
git update-index --assume-unchanged build/app/generated/source/buildConfig/debug/com/hikelocator/hikelocator/BuildConfig.java
git update-index --assume-unchanged build/app/intermediates/blame/res/debug/multi-v2/debug.json
git update-index --assume-unchanged build/app/intermediates/blame/res/debug/multi-v2/values.json
git update-index --assume-unchanged build/app/intermediates/blame/res/debug/single/debug.json
git update-index --assume-unchanged build/app/intermediates/flutter/debug/flutter_assets/LICENSE
git update-index --assume-unchanged build/app/intermediates/flutter/debug/flutter_assets/kernel_blob.bin
git update-index --assume-unchanged build/app/intermediates/flutter/debug/snapshot_blob.bin.d
git update-index --assume-unchanged build/app/intermediates/flutter/debug/snapshot_blob.bin.d.fingerprint
git update-index --assume-unchanged build/app/intermediates/flutter/flutter-x86.jar
git update-index --assume-unchanged build/app/intermediates/incremental/debug-mergeJavaRes/merge-state
git update-index --assume-unchanged build/app/intermediates/incremental/debug-mergeJavaRes/zip-cache/+P5gT6y0tluglqFnHuU363v2c2s=
git update-index --assume-unchanged build/app/intermediates/incremental/debug-mergeJavaRes/zip-cache/Hd2SONUgqFGesn1prD_jBsiYxuc=
git update-index --assume-unchanged build/app/intermediates/incremental/debug-mergeJavaRes/zip-cache/LB_8Y3afXOFysGueHFQANP7EEAQ=
git update-index --assume-unchanged build/app/intermediates/incremental/debug-mergeJavaRes/zip-cache/NKfLAyL_hJLa3E4CZhB+4sG2Phs=
git update-index --assume-unchanged build/app/intermediates/incremental/debug-mergeJavaRes/zip-cache/vBdVcninrhlicueAX06KTiRQpGk=
git update-index --assume-unchanged build/app/intermediates/incremental/debug-mergeJniLibs/merge-state
git update-index --assume-unchanged build/app/intermediates/incremental/debug-mergeJniLibs/zip-cache/+P5gT6y0tluglqFnHuU363v2c2s=
git update-index --assume-unchanged build/app/intermediates/incremental/debug-mergeJniLibs/zip-cache/Hd2SONUgqFGesn1prD_jBsiYxuc=
git update-index --assume-unchanged build/app/intermediates/incremental/debug-mergeJniLibs/zip-cache/LB_8Y3afXOFysGueHFQANP7EEAQ=
git update-index --assume-unchanged build/app/intermediates/incremental/debug-mergeJniLibs/zip-cache/NKfLAyL_hJLa3E4CZhB+4sG2Phs=
git update-index --assume-unchanged build/app/intermediates/incremental/debug-mergeJniLibs/zip-cache/vBdVcninrhlicueAX06KTiRQpGk=
git update-index --assume-unchanged build/app/intermediates/incremental/mergeDebugAssets/merger.xml
git update-index --assume-unchanged build/app/intermediates/incremental/mergeDebugJniLibFolders/merger.xml
git update-index --assume-unchanged build/app/intermediates/incremental/mergeDebugResources/compile-file-map.properties
git update-index --assume-unchanged build/app/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml
git update-index --assume-unchanged build/app/intermediates/incremental/mergeDebugResources/merger.xml
git update-index --assume-unchanged build/app/intermediates/incremental/mergeDebugShaders/merger.xml
git update-index --assume-unchanged build/app/intermediates/incremental/packageDebug/tmp/debug/dex-renamer-state.txt
git update-index --assume-unchanged build/app/intermediates/incremental/packageDebug/tmp/debug/file-input-save-data.txt
git update-index --assume-unchanged build/app/intermediates/incremental/packageDebug/tmp/debug/zip-cache/K0vrhrsOnMTwWO5bFu0zgSpD1F4=
git update-index --assume-unchanged build/app/intermediates/incremental/packageDebug/tmp/debug/zip-cache/xDgo3kRxnt9+iHcYhTuDojJ9ffY=
git update-index --assume-unchanged build/app/intermediates/javac/debug/compileDebugJavaWithJavac/classes/com/hikelocator/hikelocator/R$drawable.class
git update-index --assume-unchanged build/app/intermediates/javac/debug/compileDebugJavaWithJavac/classes/com/hikelocator/hikelocator/R$mipmap.class
git update-index --assume-unchanged build/app/intermediates/javac/debug/compileDebugJavaWithJavac/classes/com/hikelocator/hikelocator/R$style.class
git update-index --assume-unchanged build/app/intermediates/javac/debug/compileDebugJavaWithJavac/classes/com/hikelocator/hikelocator/R.class
git update-index --assume-unchanged build/app/intermediates/javac/debug/compileDebugJavaWithJavac/classes/io/flutter/plugins/GeneratedPluginRegistrant.class
git update-index --assume-unchanged build/app/intermediates/merged_assets/debug/mergeDebugAssets/out/flutter_assets/LICENSE
git update-index --assume-unchanged build/app/intermediates/merged_assets/debug/mergeDebugAssets/out/flutter_assets/kernel_blob.bin
git update-index --assume-unchanged build/app/intermediates/merged_manifests/debug/processDebugManifest/merged/AndroidManifest.xml
git update-index --assume-unchanged build/app/intermediates/processed_res/debug/processDebugResources/out/resources-debug.ap_
git update-index --assume-unchanged build/app/intermediates/res/merged/debug/drawable_launch_background.xml.flat
git update-index --assume-unchanged build/app/intermediates/res/merged/debug/mipmap-hdpi_ic_launcher.png.flat
git update-index --assume-unchanged build/app/intermediates/res/merged/debug/mipmap-mdpi_ic_launcher.png.flat
git update-index --assume-unchanged build/app/intermediates/res/merged/debug/mipmap-xhdpi_ic_launcher.png.flat
git update-index --assume-unchanged build/app/intermediates/res/merged/debug/mipmap-xxhdpi_ic_launcher.png.flat
git update-index --assume-unchanged build/app/intermediates/res/merged/debug/mipmap-xxxhdpi_ic_launcher.png.flat
git update-index --assume-unchanged build/app/intermediates/res/merged/debug/values_values.arsc.flat
git update-index --assume-unchanged build/app/intermediates/transforms/dexBuilder/debug/2.jar
git update-index --assume-unchanged build/app/intermediates/transforms/dexBuilder/debug/3.jar
git update-index --assume-unchanged build/app/intermediates/transforms/dexBuilder/debug/4.jar
git update-index --assume-unchanged build/app/intermediates/transforms/dexBuilder/debug/5.jar
git update-index --assume-unchanged build/app/intermediates/transforms/dexBuilder/debug/6.jar
git update-index --assume-unchanged build/app/intermediates/transforms/dexBuilder/debug/7.jar
git update-index --assume-unchanged build/app/intermediates/transforms/dexBuilder/debug/8/com/hikelocator/hikelocator/BuildConfig.dex
git update-index --assume-unchanged build/app/intermediates/transforms/dexBuilder/debug/8/com/hikelocator/hikelocator/R$drawable.dex
git update-index --assume-unchanged build/app/intermediates/transforms/dexBuilder/debug/8/com/hikelocator/hikelocator/R$mipmap.dex
git update-index --assume-unchanged build/app/intermediates/transforms/dexBuilder/debug/8/com/hikelocator/hikelocator/R$style.dex
git update-index --assume-unchanged build/app/intermediates/transforms/dexBuilder/debug/8/com/hikelocator/hikelocator/R.dex
git update-index --assume-unchanged build/app/intermediates/transforms/dexBuilder/debug/8/io/flutter/plugins/GeneratedPluginRegistrant.dex
git update-index --assume-unchanged build/app/intermediates/transforms/dexBuilder/debug/9/com/hikelocator/hikelocator/MainActivity.dex
git update-index --assume-unchanged build/app/intermediates/transforms/dexBuilder/debug/__content__.json
git update-index --assume-unchanged build/app/intermediates/transforms/dexMerger/debug/0/classes.dex
git update-index --assume-unchanged build/app/intermediates/transforms/dexMerger/debug/__content__.json
git update-index --assume-unchanged build/app/intermediates/transforms/externalLibsDexMerger/debug/0/classes.dex
git update-index --assume-unchanged build/app/intermediates/transforms/mergeJavaRes/debug/0.jar
git update-index --assume-unchanged build/app/intermediates/transforms/mergeJavaRes/debug/__content__.json
git update-index --assume-unchanged build/app/intermediates/transforms/mergeJniLibs/debug/__content__.json
git update-index --assume-unchanged build/app/kotlin/compileDebugKotlin/build-history.bin
git update-index --assume-unchanged build/app/kotlin/compileDebugKotlin/caches-jvm/inputs/source-to-output.tab.keystream
git update-index --assume-unchanged build/app/kotlin/compileDebugKotlin/caches-jvm/inputs/source-to-output.tab.keystream.len
git update-index --assume-unchanged build/app/kotlin/compileDebugKotlin/caches-jvm/inputs/source-to-output.tab.values.at
git update-index --assume-unchanged build/app/kotlin/compileDebugKotlin/caches-jvm/inputs/source-to-output.tab_i
git update-index --assume-unchanged build/app/kotlin/compileDebugKotlin/caches-jvm/jvm/kotlin/class-fq-name-to-source.tab
git update-index --assume-unchanged build/app/kotlin/compileDebugKotlin/caches-jvm/jvm/kotlin/class-fq-name-to-source.tab.values.at
git update-index --assume-unchanged build/app/kotlin/compileDebugKotlin/caches-jvm/jvm/kotlin/internal-name-to-source.tab.values.at
git update-index --assume-unchanged build/app/kotlin/compileDebugKotlin/caches-jvm/jvm/kotlin/source-to-classes.tab
git update-index --assume-unchanged build/app/kotlin/compileDebugKotlin/caches-jvm/jvm/kotlin/source-to-classes.tab.keystream
git update-index --assume-unchanged build/app/kotlin/compileDebugKotlin/caches-jvm/jvm/kotlin/source-to-classes.tab.keystream.len
git update-index --assume-unchanged build/app/kotlin/compileDebugKotlin/caches-jvm/jvm/kotlin/source-to-classes.tab_i
git update-index --assume-unchanged build/app/kotlin/compileDebugKotlin/caches-jvm/lookups/counters.tab
git update-index --assume-unchanged build/app/kotlin/compileDebugKotlin/caches-jvm/lookups/file-to-id.tab.keystream
git update-index --assume-unchanged build/app/kotlin/compileDebugKotlin/caches-jvm/lookups/file-to-id.tab.keystream.len
git update-index --assume-unchanged build/app/kotlin/compileDebugKotlin/caches-jvm/lookups/file-to-id.tab_i
git update-index --assume-unchanged build/app/kotlin/compileDebugKotlin/caches-jvm/lookups/id-to-file.tab.values.at
git update-index --assume-unchanged build/app/kotlin/compileDebugKotlin/last-build.bin
git update-index --assume-unchanged build/app/outputs/apk/app.apk
git update-index --assume-unchanged build/app/outputs/apk/app.apk.sha1
git update-index --assume-unchanged build/app/outputs/apk/debug/app-debug.apk
git update-index --assume-unchanged build/app/outputs/logs/manifest-merger-debug-report.txt
git update-index --assume-unchanged build/frontend_server.d
git update-index --assume-unchanged pubspec.lock

git update-index --assume-unchanged build/app/intermediates/javac/debug/compileDebugJavaWithJavac/classes/com/hikelocator/hikelocator/R$drawable.class
git update-index --assume-unchanged build/app/intermediates/javac/debug/compileDebugJavaWithJavac/classes/com/hikelocator/hikelocator/R$mipmap.class
git update-index --assume-unchanged build/app/intermediates/javac/debug/compileDebugJavaWithJavac/classes/com/hikelocator/hikelocator/R$style.class
git update-index --assume-unchanged build/app/intermediates/transforms/dexBuilder/debug/8/com/hikelocator/hikelocator/R$drawable.dex
git update-index --assume-unchanged build/app/intermediates/transforms/dexBuilder/debug/8/com/hikelocator/hikelocator/R$mipmap.dex
git update-index --assume-unchanged build/app/intermediates/transforms/dexBuilder/debug/8/com/hikelocator/hikelocator/R$style.dex
